pkg/compare/compare.go, pkg/compare/testdata/ManualCorrelationMatchesArePrioritizedOverGroupCorrelation/liveout.golden, pkg/compare/testdata/ManualCorrelationMatchesArePrioritizedOverGroupCorrelation/localout.golden, pkg/compare/testdata/ReffTemplateInSubDirNotReportedMissing/liveout.golden, pkg/compare/testdata/ReffTemplateInSubDirNotReportedMissing/localout.golden, pkg/compare/testdata/ReffTemplateInSubDirWorksWithManualCorrelation/liveout.golden, pkg/compare/testdata/ReffTemplateInSubDirWorksWithManualCorrelation/localout.golden, pkg/compare/testdata/ReffWithTemplateFunctionsRendersAsExpected/liveout.golden, pkg/compare/testdata/ReffWithTemplateFunctionsRendersAsExpected/localout.golden
The reference configuration is the "baseline" and the live cluster is what is being validated. Reversing the order in the diff ensures that the + means "live cluster has this additional line" and - means "live cluster is missing this line"
=> Reverse the left/right terms in the diff

.gitignore, .goreleaser.yml, Makefile, docs/release-guide.md
This commit adds the `release` and `release-dry-run` endpoints to the Makefile. These endpoints use Goreleaser to build the compare binary for different architectures and platforms. The `release-dry-run` endpoint only builds the binaries, creates the archives, and generates the release notes. The `release` endpoint also uploads the release to GitHub. The release notes contain a list of all the changes from the previous tag to the newest tag.
=> Add release endpoint to Makefile

pkg/compare/compare.go
Change kubectl prefix in help message to show the correct command for standalone
=> CNF-12627: Change kubectl prefix in help message

pkg/compare/compare.go, pkg/compare/compare_test.go, pkg/compare/testdata/InvalidResourcesAreSkipped/localerr.golden, pkg/compare/testdata/InvalidResourcesAreSkipped/localout.golden, pkg/compare/testdata/InvalidResourcesAreSkipped/reference/deploymentDashboard.yaml, pkg/compare/testdata/InvalidResourcesAreSkipped/reference/deploymentMetrics.yaml, pkg/compare/testdata/InvalidResourcesAreSkipped/reference/metadata.yaml, pkg/compare/testdata/InvalidResourcesAreSkipped/resources/d1.json, pkg/compare/testdata/InvalidResourcesAreSkipped/resources/d2.yaml, pkg/compare/testdata/InvalidResourcesAreSkipped/resources/d3.yaml, pkg/compare/testdata/InvalidResourcesAreSkipped/resources/d4.yaml
previously, when using the command in local mode with recursive mode enabled, the command would attempt to parse additional JSON/YAML files as resources. If any files were invalid, an error was presented to the user, and the compare results for other valid resources were not returned.
With this update, the command will now issue a warning for invalid resources instead of stopping execution. It will skip these problematic files and proceed to present the compare results for the valid resources.
=> Change command behavior to skip invalid resources in local mode

pkg/compare/compare_test.go, pkg/compare/parsing.go, pkg/compare/testdata/RefContainsTemplatesWithFunctionTemplatesInSameFile/localerr.golden, pkg/compare/testdata/RefContainsTemplatesWithFunctionTemplatesInSameFile/localout.golden, pkg/compare/testdata/RefContainsTemplatesWithFunctionTemplatesInSameFile/reference/cm.yaml, pkg/compare/testdata/RefContainsTemplatesWithFunctionTemplatesInSameFile/reference/metadata.yaml, pkg/compare/testdata/RefContainsTemplatesWithFunctionTemplatesInSameFile/resources/cm.yaml
When using template functions that are declared in the same file as
the templates, an error would be returned specifying that the function
is not found. This commit fixes this behavior and also adds a test case 
that ensures that the bug has been fixed.
=> Fix use of template functions declared in the same file

Dockerfile, Makefile, README.md, docs/image-build.md
- Add Dockerfile
- Modify makefile to support cross-platform build
Building the image
```bash
make image-build 
```
Getting the binaries
```bash
➜ podman run --platform linux/amd64 -it --entrypoint /bin/bash kube-compare
[root@f1b611b07d36 /]# ls
afs  bin  boot	dev  etc  home	lib  lib64  lost+found	media  mnt  opt  proc  root  run  sbin	srv  sys  tmp  usr  var
[root@f1b611b07d36 /]# ls /usr/share/openshift
LICENSE  linux_amd64  linux_arm64  linux_ppc64le  linux_s390x  mac  mac_arm64  windows
```
Based on [oc cli-artifacts](https://github.com/openshift/oc/blob/master/images/cli-artifacts/Dockerfile.rhel) image
=> CNF-13524: Add Dockerfile

Dockerfile, docs/image-build.md
Using scratch as base image to effectively remove any security concerns and use the container as simple storage for all the binaries 
https://hub.docker.com/_/scratch/ 
tested with `quay.io/npathan/dev:kc-8-2`
/cc @natifridman 
/cc @nocturnalastro
=> use scratch as final base image

pkg/compare/compare.go, pkg/compare/compare_test.go, pkg/compare/correlator.go, pkg/compare/parsing.go, pkg/compare/testdata/TemplateIsntYAMLAfterExecutionWithEmptyMap/localerr.golden
Remove extractMetadata, moving metadata into the ReferenceTemplate. 
This allows moves errors that may occur with extracting the metadata
earlier in the process.
Also move error wrap into the stored error message string to simplify
generation of the error.
=> Move metadata to ReferenceTemplate and do some cleanup

README.md, pkg/compare/compare.go, pkg/compare/compare_test.go, pkg/compare/parsing.go, pkg/compare/testdata/NoDiffs/localerr.golden, pkg/compare/testdata/NoInput/localerr.golden, pkg/compare/testdata/ReferenceConfigFileDoesntExist/localerr.golden, pkg/compare/testdata/ReferenceDirectoryDoesntExist/localerr.golden, pkg/compare/testdata/YAMLOutput/localout.golden
Point to config file instead of a directory
Before:
```
kubectl cluster-compare -r ./reference
```
After:
```
kubectl cluster-compare -r ./reference/metadata.yaml
```
=> CNF-13744: Point reference flag to config file

Dockerfile, Makefile
Ref ticket: https://issues.redhat.com/browse/ART-10503
- Use openshift-enterprise-cli as base
- Remove `go work vendor` before build step
- Ensure -mod=vendor when building
=> Onboarding new component to OCP

.github/dependabot.yml
=> Configure dependabot to do go vendoring

.github/dependabot.yml
This reverts commit 2ca34908b971c0f00e803433063e40692cbd8fee.
=> Revert "Configure dependabot to do go vendoring"

pkg/compare/compare.go, pkg/compare/testdata/WhenUsingDiffAllFlag-AllUnmatchedResourcesAppearInSummary/localout.golden, pkg/compare/testdata/WhenUsingDiffAllFlag-AllUnmatchedResourcesAppearInSummary/reference/apps.v1.DaemonSet.kube-system.kindnet.yaml
In the case where a patch can not be made for one of the templates it will fallback to the old method of counting the number of lines
=> CNF-14097: Count leaves of the patch to find smallest diff

docs/reference-config-guide-v2.md, pkg/compare/compare.go, pkg/compare/compare_test.go, pkg/compare/parsing.go, pkg/compare/referenceV1.go, pkg/compare/referenceV2.go, pkg/compare/testdata/ReferenceV2InlineRegex/localWithDiffInFirstLineerr.golden, pkg/compare/testdata/ReferenceV2InlineRegex/localWithDiffInFirstLineout.golden, pkg/compare/testdata/ReferenceV2InlineRegex/localinvalidRegexerr.golden, pkg/compare/testdata/ReferenceV2InlineRegex/localout.golden, pkg/compare/testdata/ReferenceV2InlineRegex/localwithDifferr.golden, pkg/compare/testdata/ReferenceV2InlineRegex/localwithDiffout.golden, pkg/compare/testdata/ReferenceV2InlineRegex/reference/cm-invalidregex.yaml, pkg/compare/testdata/ReferenceV2InlineRegex/reference/cm-regex-with-diff-in-first-line.yaml, pkg/compare/testdata/ReferenceV2InlineRegex/reference/cm-regex-with-diff.yaml, pkg/compare/testdata/ReferenceV2InlineRegex/reference/cm.yaml, pkg/compare/testdata/ReferenceV2InlineRegex/reference/metadata-invalid-regex.yaml, pkg/compare/testdata/ReferenceV2InlineRegex/reference/metadata-regex-with-diff-in-first-line.yaml, pkg/compare/testdata/ReferenceV2InlineRegex/reference/metadata-regex-with-diff.yaml, pkg/compare/testdata/ReferenceV2InlineRegex/reference/metadata.yaml, pkg/compare/testdata/ReferenceV2InlineRegex/resources/cm.yaml, pkg/compare/testdata/ReferenceV2PerFieldMatcherValidation/localmatcherNotExisterr.golden, pkg/compare/testdata/ReferenceV2PerFieldMatcherValidation/localpathNotItTemplateerr.golden, pkg/compare/testdata/ReferenceV2PerFieldMatcherValidation/reference/cm.yaml, pkg/compare/testdata/ReferenceV2PerFieldMatcherValidation/reference/metadata-does-not-exist.yaml, pkg/compare/testdata/ReferenceV2PerFieldMatcherValidation/reference/metadata-path-does-not-exist-in-template.yaml, pkg/compare/testdata/ReferenceV2PerFieldMatcherValidation/resources/cm.yaml
This update adds the option to include common inline diff
functions in the tool.  Diff functions may simplify complex 
diff logic, which would be hard to write and read using  regular Go templating and include a more tidy usage.
A new regex inline diff function allows checking fields in cluster resources against a regex pattern. If a  field matches the regex, no diffs are shown; if it doesn’t  match, a diff will highlight the difference. To use this,  enable `regexInline` for the field in `metadata.yaml`
and add the regex in the template.
([CNF-14934](https://issues.redhat.com//browse/CNF-14934))
=> Add regex inline diff function

docs/user-guide.md, pkg/compare/compare.go, pkg/compare/compare_test.go, pkg/compare/correlator.go, pkg/compare/parsing.go, pkg/compare/testdata/StrictMatch/localerr.golden, pkg/compare/testdata/StrictMatch/localout.golden, pkg/compare/testdata/StrictMatch/localstrict_mode_onerr.golden, pkg/compare/testdata/StrictMatch/localstrict_mode_onout.golden, pkg/compare/testdata/StrictMatch/reference/deploymentDashboard.yaml, pkg/compare/testdata/StrictMatch/reference/deploymentMetrics.yaml, pkg/compare/testdata/StrictMatch/reference/metadata.yaml, pkg/compare/testdata/StrictMatch/resources/d2.yaml, pkg/compare/testdata/StrictMatch/resources/deploymentDashboard.yaml, pkg/compare/testdata/StrictMatch/userconfig.yaml
The default template correlator search is now a fuzzy match, allowing
detection of CRs that have a different name or namespace, but otherwise
match a template.
A user config flag reverts to the previous behavior.
=> OCPBUGS-44249: Introduce strictMatch correlation flag

docs/reference-config-guide-v2.md, pkg/compare/capturegroupsInlineDiff.go, pkg/compare/capturegroupsInlineDiff_test.go, pkg/compare/compare.go, pkg/compare/compare_test.go, pkg/compare/referenceV2.go, pkg/compare/regexInlineDiff.go, pkg/compare/regexInlineDiff_test.go, pkg/compare/testdata/ReferenceV2InlineCapturegroups/localWithDiffAcrossCapturegroupsAndRegexMismatcherr.golden, pkg/compare/testdata/ReferenceV2InlineCapturegroups/localWithDiffAcrossCapturegroupsAndRegexMismatchout.golden, pkg/compare/testdata/ReferenceV2InlineCapturegroups/localWithDiffAcrossCapturegroupsAndRegexout.golden, pkg/compare/testdata/ReferenceV2InlineCapturegroups/localWithDiffAcrossCapturegroupsMismatcherr.golden, pkg/compare/testdata/ReferenceV2InlineCapturegroups/localWithDiffAcrossCapturegroupsMismatchout.golden, pkg/compare/testdata/ReferenceV2InlineCapturegroups/localWithDiffAcrossCapturegroupsout.golden, pkg/compare/testdata/ReferenceV2InlineCapturegroups/reference/cm-with-diff-across-capturegroups-mismatch.yaml, pkg/compare/testdata/ReferenceV2InlineCapturegroups/reference/cm-with-diff-across-capturegroups.yaml, pkg/compare/testdata/ReferenceV2InlineCapturegroups/reference/metadata-with-diff-across-capture-groups-and-regex-mismatch.yaml, pkg/compare/testdata/ReferenceV2InlineCapturegroups/reference/metadata-with-diff-across-capture-groups-and-regex.yaml, pkg/compare/testdata/ReferenceV2InlineCapturegroups/reference/metadata-with-diff-across-capture-groups-mismatch.yaml, pkg/compare/testdata/ReferenceV2InlineCapturegroups/reference/metadata-with-diff-across-capture-groups.yaml, pkg/compare/testdata/ReferenceV2InlineCapturegroups/resources/multi-mismatch.yaml, pkg/compare/testdata/ReferenceV2InlineCapturegroups/resources/multi.yaml
- **Omit actual metadata hash from most end-to-end tests to simplify test output comparison**
- **Enforce capture group contents across multiple fields within an object**
- **Run InlineDiff in a 2-phase loop; once to capture all capturegroups, and once to use them**
=> CNF-15603: Corellate capture groups across objects

addon-tools/helm-convert/README.md, addon-tools/helm-convert/convert/convert.go, addon-tools/helm-convert/convert/convert_test.go, addon-tools/helm-convert/convert/testdata/CapturegroupDefaults/reference/metadata.yaml, addon-tools/helm-convert/convert/testdata/CapturegroupDefaults/reference/sa.yaml, addon-tools/helm-convert/convert/testdata/CapturegroupDefaults/reference/secret.yaml, addon-tools/helm-convert/convert/testdata/CapturegroupDefaults/result/Chart.yaml, addon-tools/helm-convert/convert/testdata/CapturegroupDefaults/result/templates/sa.yaml, addon-tools/helm-convert/convert/testdata/CapturegroupDefaults/result/templates/secret.yaml, addon-tools/helm-convert/convert/testdata/CapturegroupDefaults/result/values.yaml, addon-tools/helm-convert/convert/testdata/CapturegroupDefaults/values.yaml
- **helm-convert: Change --version to --helm-version to stop collisions with the native --version flag**
- **helm-convert: Enable capturegroup default substitution**
As detailed in the doc changes, this allows us to substitute defaults into
capturegroups when creating the associated helm chart, for cases when we don't
want the capturegroups to be visible in the resulting CRs.
Prerequisite for https://issues.redhat.com/browse/OCPBUGS-47784
=> helm-convert: Enable capturegroup default substitution

docs/user-guide.md, pkg/compare/compare.go, pkg/compare/compare_test.go, pkg/compare/correlator.go, pkg/compare/testdata/TwoTemplatesWithSameKindNamespace/localVerboseerr.golden, pkg/compare/testdata/TwoTemplatesWithSameKindNamespace/localVerboseout.golden, pkg/compare/testdata/TwoTemplatesWithSameapiVersionKindNameNamespace/localVerboseout.golden, pkg/compare/testdata/TwoTemplatesWithSameapiVersionKindNameNamespace/localout.golden, pkg/compare/testdata/WhenUsingDiffAllFlag-AllUnmatchedResourcesAppearInSummary/localout.golden
The specific issues are revealed when `--verbose` output is enabled.
=> OCPBUGS-50707: Hide all reference correlation overlaps behind a single warning

docs/user-guide.md, pkg/compare/compare.go, pkg/compare/compare_test.go, pkg/compare/correlator.go, pkg/compare/testdata/TwoTemplatesWithSameKindNamespace/localVerboseerr.golden, pkg/compare/testdata/TwoTemplatesWithSameKindNamespace/localVerboseout.golden, pkg/compare/testdata/TwoTemplatesWithSameapiVersionKindNameNamespace/localVerboseout.golden, pkg/compare/testdata/TwoTemplatesWithSameapiVersionKindNameNamespace/localout.golden, pkg/compare/testdata/WhenUsingDiffAllFlag-AllUnmatchedResourcesAppearInSummary/localout.golden
The specific issues are revealed when `--verbose` output is enabled.
=> [release-4.18] OCPBUGS-50810: Hide all reference correlation overlaps behind a single warning

docs/contributing.md, hack/golangci-lint.sh
- **Fix golint script to work without 'go work'**
- **Update contributing guide to match removal of the go workspace**
=> Final cleanup for removal of the go workspace configuration

pkg/compare/capturegroupsInlineDiff.go, pkg/compare/capturegroupsInlineDiff_test.go, pkg/compare/compare.go, pkg/compare/testdata/ReferenceV2InlineCapturegroups/localinvalidCapturegroupsLateDetectionout.golden, pkg/compare/testdata/ReferenceV2InlineCapturegroups/localinvalidCapturegroupserr.golden, pkg/compare/testdata/ReferenceV2InlineCapturegroups/reference/cm-invalid-capturegroups-late-detection.yaml, pkg/compare/testdata/ReferenceV2InlineCapturegroups/reference/cm-invalid-capturegroups.yaml
- **Add capturegroup debugging details to verbose output**
- **Add full capturegroup text to CgInfo structure**
- **Implement better capturegroup escape mechanism**
- **Allow spaces in capturegroup regexes**
=> OCPBUGS-51191: Sanitize capturegrouos against partial matches

pkg/compare/capturegroupsInlineDiff.go, pkg/compare/capturegroupsInlineDiff_test.go, pkg/compare/compare.go, pkg/compare/testdata/ReferenceV2InlineCapturegroups/localinvalidCapturegroupsLateDetectionout.golden, pkg/compare/testdata/ReferenceV2InlineCapturegroups/localinvalidCapturegroupserr.golden, pkg/compare/testdata/ReferenceV2InlineCapturegroups/reference/cm-invalid-capturegroups-late-detection.yaml, pkg/compare/testdata/ReferenceV2InlineCapturegroups/reference/cm-invalid-capturegroups.yaml
- **Add capturegroup debugging details to verbose output**
- **Add full capturegroup text to CgInfo structure**
- **Implement better capturegroup escape mechanism**
- **Allow spaces in capturegroup regexes**
=> OCPBUGS-51306: capturegroup regex collision 4.18

pkg/compare/capturegroupsInlineDiff.go, pkg/compare/compare.go, pkg/compare/compare_test.go, pkg/compare/testdata/MultitemplateTieBreaker/localerr.golden, pkg/compare/testdata/MultitemplateTieBreaker/localfieldMismatcherr.golden, pkg/compare/testdata/MultitemplateTieBreaker/localfieldMismatchout.golden, pkg/compare/testdata/MultitemplateTieBreaker/locallengthMismatcherr.golden, pkg/compare/testdata/MultitemplateTieBreaker/locallengthMismatchout.golden, pkg/compare/testdata/MultitemplateTieBreaker/localout.golden, pkg/compare/testdata/MultitemplateTieBreaker/reference/cm-correct.yaml, pkg/compare/testdata/MultitemplateTieBreaker/reference/cm-extra-field.yaml, pkg/compare/testdata/MultitemplateTieBreaker/reference/cm-missing-field.yaml, pkg/compare/testdata/MultitemplateTieBreaker/reference/cm-same-fields-too-long.yaml, pkg/compare/testdata/MultitemplateTieBreaker/reference/cm-same-fields-too-short.yaml, pkg/compare/testdata/MultitemplateTieBreaker/reference/metadata-field-mismatch.yaml, pkg/compare/testdata/MultitemplateTieBreaker/reference/metadata-length-mismatch.yaml, pkg/compare/testdata/MultitemplateTieBreaker/reference/metadata.yaml, pkg/compare/testdata/MultitemplateTieBreaker/resources/cm.yaml, pkg/compare/testdata/NoDiffs/localwithVebosityFlagout.golden, pkg/compare/testdata/ReferenceV2InlineCapturegroups/localinvalidCapturegroupsLateDetectionout.golden, pkg/compare/testdata/ReferenceV2PerFieldMatcherValidation/localpathNotItTemplateerr.golden, pkg/compare/testdata/SomeDiffs/localwithVebosityFlagout.golden, pkg/compare/testdata/TwoTemplatesWithSameKindNamespace/localVerboseout.golden, pkg/compare/testdata/TwoTemplatesWithSameapiVersionKindNameNamespace/localVerboseout.golden
- **Tighten up verbose messages for comparison and correlation debugging**
- **Use a diffscore and not mergepatch leafCount to decide between multiple matches**
=> OCPBUGS-53199: Use diff size as multi-match tiebreaker

pkg/compare/capturegroupsInlineDiff.go, pkg/compare/compare.go, pkg/compare/compare_test.go, pkg/compare/testdata/MultitemplateTieBreaker/localerr.golden, pkg/compare/testdata/MultitemplateTieBreaker/localfieldMismatcherr.golden, pkg/compare/testdata/MultitemplateTieBreaker/localfieldMismatchout.golden, pkg/compare/testdata/MultitemplateTieBreaker/locallengthMismatcherr.golden, pkg/compare/testdata/MultitemplateTieBreaker/locallengthMismatchout.golden, pkg/compare/testdata/MultitemplateTieBreaker/localout.golden, pkg/compare/testdata/MultitemplateTieBreaker/reference/cm-correct.yaml, pkg/compare/testdata/MultitemplateTieBreaker/reference/cm-extra-field.yaml, pkg/compare/testdata/MultitemplateTieBreaker/reference/cm-missing-field.yaml, pkg/compare/testdata/MultitemplateTieBreaker/reference/cm-same-fields-too-long.yaml, pkg/compare/testdata/MultitemplateTieBreaker/reference/cm-same-fields-too-short.yaml, pkg/compare/testdata/MultitemplateTieBreaker/reference/metadata-field-mismatch.yaml, pkg/compare/testdata/MultitemplateTieBreaker/reference/metadata-length-mismatch.yaml, pkg/compare/testdata/MultitemplateTieBreaker/reference/metadata.yaml, pkg/compare/testdata/MultitemplateTieBreaker/resources/cm.yaml, pkg/compare/testdata/NoDiffs/localwithVebosityFlagout.golden, pkg/compare/testdata/ReferenceV2InlineCapturegroups/localinvalidCapturegroupsLateDetectionout.golden, pkg/compare/testdata/ReferenceV2PerFieldMatcherValidation/localpathNotItTemplateerr.golden, pkg/compare/testdata/SomeDiffs/localwithVebosityFlagout.golden, pkg/compare/testdata/TwoTemplatesWithSameKindNamespace/localVerboseout.golden, pkg/compare/testdata/TwoTemplatesWithSameapiVersionKindNameNamespace/localVerboseout.golden
- **Tighten up verbose messages for comparison and correlation debugging**
- **Use a diffscore and not mergepatch leafCount to decide between multiple matches**
=> OCPBUGS-53409: diff tie breaker 4.18

addon-tools/helm-convert/README.md, addon-tools/helm-convert/convert/convert.go, addon-tools/helm-convert/convert/convert_test.go, addon-tools/helm-convert/convert/testdata/LookupSubstitution/reference/cm.yaml, addon-tools/helm-convert/convert/testdata/LookupSubstitution/reference/metadata.yaml, addon-tools/helm-convert/convert/testdata/LookupSubstitution/result/Chart.yaml, addon-tools/helm-convert/convert/testdata/LookupSubstitution/result/templates/cm.yaml, addon-tools/helm-convert/convert/testdata/LookupSubstitution/result/values.yaml, addon-tools/helm-convert/convert/testdata/LookupSubstitution/values.yaml, docs/reference-config-guide-v2.md, pkg/compare/compare.go, pkg/compare/compare_test.go, pkg/compare/correlator.go, pkg/compare/funcmap.go, pkg/compare/referenceV1.go, pkg/compare/referenceV2.go, pkg/compare/testdata/LookupCRs/localout.golden, pkg/compare/testdata/LookupCRs/reference/cm-lookupCR.yaml, pkg/compare/testdata/LookupCRs/reference/cm-lookupCRs.yaml, pkg/compare/testdata/LookupCRs/reference/deploymentDashboard.yaml, pkg/compare/testdata/LookupCRs/reference/deploymentMetrics.yaml, pkg/compare/testdata/LookupCRs/reference/metadata-lookupCR.yaml, pkg/compare/testdata/LookupCRs/reference/metadata.yaml, pkg/compare/testdata/LookupCRs/resources/cm.yaml, pkg/compare/testdata/LookupCRs/resources/deploymentDashboard.yaml, pkg/compare/testdata/LookupCRs/resources/deploymentMetrics.yaml, pkg/compare/testdata/NoDiffs/localwithVebosityFlagout.golden, pkg/compare/testdata/SomeDiffs/localwithVebosityFlagout.golden, pkg/compare/testdata/TwoTemplatesWithSameKindNamespace/localVerboseout.golden, pkg/compare/testdata/TwoTemplatesWithSameapiVersionKindNameNamespace/localVerboseout.golden
- **Cleanup verbose logging by using klog.V(1) where possible**
- **Split main resource fetch and process into 2 steps**
- **Introduce 'lookupCRs' 'lookupCR' template functions**
- **helm-convert: Minor refactor and cleanup**
- **Add capability to override lookup functions in helm-convert tool**
=> CNF-16041: Add 'lookupCR' and 'lookupCRs' template functions for cross-object references

docs/reference-config-guide-v2.md, pkg/compare/compare.go, pkg/compare/compare_test.go, pkg/compare/funcmap.go, pkg/compare/testdata/DoNotMatch/localFilterout.golden, pkg/compare/testdata/DoNotMatch/localNoMatcherr.golden, pkg/compare/testdata/DoNotMatch/localNoMatchout.golden, pkg/compare/testdata/DoNotMatch/localout.golden, pkg/compare/testdata/DoNotMatch/reference/d1-anyname.yaml, pkg/compare/testdata/DoNotMatch/reference/match.yaml, pkg/compare/testdata/DoNotMatch/reference/metadata-filter.yaml, pkg/compare/testdata/DoNotMatch/reference/metadata-nomatch.yaml, pkg/compare/testdata/DoNotMatch/reference/metadata.yaml, pkg/compare/testdata/DoNotMatch/reference/nevermatch.yaml, pkg/compare/testdata/DoNotMatch/resources/cm.yaml, pkg/compare/testdata/DoNotMatch/resources/d1.yaml, pkg/compare/testdata/DoNotMatch/resources/d2.yaml
This allows templates to actively opt-out of matching certain CRs.
For example, this can be useful for nameless templates which would
otherwise match too many CRs. if there is some other criteria for
inclusion/exclusion, the template may check and call the `doNotMatch`
function if it should not be allowed to match the current CR.
See `d1-anyname.yaml` for a contrived but useful example.
=> OCPBUGS-44249: Introduce 'doNotMatch' template function
