.gitignore, Makefile, hack/markdownlint-install.sh, hack/markdownlint.Dockerfile, hack/markdownlint.sh
/cc @AlinaSecret
/cc @imiller0 
Next need update /openshift/release
=> markdown linter

.markdownlint-cli2.yaml, README.md, docs/reference-config-guide.md, docs/user-guide.md
few edits and config file for linter
=> clean up markdown for linter

docs/reference-config-guide.md, docs/user-guide.md
See some suggested updates for the user guide.
=> updates on UserGuide

addon-tools/report-creator/report/create_test.go, pkg/compare/compare.go, pkg/compare/compare_test.go, pkg/compare/httpfs.go, pkg/compare/parsing.go
Made to show the issues raised by golangci-lint for issue https://github.com/openshift/kube-compare/issues/22
=> fix issues from golangci-lint

.golangci.yml, addon-tools/report-creator/junit/junit.go, addon-tools/report-creator/report/create.go, addon-tools/report-creator/report/create_test.go, addon-tools/report-creator/report/testdata/Creation Of Missing CRs And Unmatched CRs And Diff Tests Suites When No Diffs Creation Of Missing CRs And Unmatched CRs And Diff Tests Suites When No Diffs.golden, addon-tools/report-creator/report/testdata/Diff Test Suite Creation When There Are Diffs Diff Test Suite Creation When There Are Diffs.golden, addon-tools/report-creator/report/testdata/Missing CRs test suite creation when CRS are Missing Missing CRs test suite creation when CRS are Missing.golden, addon-tools/report-creator/report/testdata/Unmatched CRs Test Suite When CRs Are Unmatched Unmatched CRs Test Suite When CRs Are Unmatched.golden, cmd/kubectl-cluster_compare.go, pkg/compare/compare.go, pkg/compare/compare_test.go, pkg/compare/correlator.go, pkg/compare/httpfs.go, pkg/compare/parsing.go, pkg/compare/testdata/TemplateHasNoKind/liveerr.golden, pkg/compare/testdata/TemplateIsntYAMLAfterExecutionWithEmptyMap/localerr.golden, pkg/compare/testdata/TestLocalResourceFileDoesntexist/localerr.golden, pkg/groups/groups.go
/cc @pixelsoccupied @AlinaSecret
=> Fix linting extended linters

Makefile, README.md
Minor tweaks to the Makefile and README.md based on my first experience installing the tool
=> Readme usability test: installation

Makefile
Search order: podman, docker
Also makes sure our command line options match what the engine(s) need:
- Podman needs volumes mounted with `:Z`
- Docker needs a socket path
=> Autodetct the container engine if not set

pkg/compare/compare.go, pkg/compare/correlator.go, pkg/compare/parsing.go, pkg/compare/testdata/AllRequiredTemplatesExistAndThereAreNoDiffs/liveout.golden, pkg/compare/testdata/AllRequiredTemplatesExistAndThereAreNoDiffs/localout.golden, pkg/compare/testdata/DiffinCustomOmittedFieldsIsntShown/liveout.golden, pkg/compare/testdata/DiffinCustomOmittedFieldsIsntShown/localout.golden, pkg/compare/testdata/DiffinCustomOmittedFieldsIsntShownAllQuoted/localout.golden, pkg/compare/testdata/DiffinCustomOmittedFieldsIsntShownLeadingDot/localout.golden, pkg/compare/testdata/DiffinCustomOmittedFieldsIsntShownNonDefault/localout.golden, pkg/compare/testdata/DiffinCustomOmittedFieldsIsntShownPrefix/localout.golden, pkg/compare/testdata/ManualCorrelationMatchesArePrioritizedOverGroupCorrelation/liveout.golden, pkg/compare/testdata/ManualCorrelationMatchesArePrioritizedOverGroupCorrelation/localout.golden, pkg/compare/testdata/WhenUsingDiffAllFlag-AllUnmatchedResourcesAppearInSummary/localout.golden
=> CNF-14098: Count each CR for the same template in total

.goreleaser.yml
=> Modify go-releaser to build arm64 and not 386

README.md
Added command line for plugin installation with Krew.
=> Added krew installation guide in install section

docs/downstream.md
=> Add downstream build documentation

docs/release-guide.md, hack/krew-bump.sh
=> Add krew-bump.sh helper script for updating the krew index as part of release

.goreleaser.yml
=> fix report-creator release

pkg/compare/compare_test.go, pkg/compare/testdata/ReferenceV2DiffinCustomOmittedFieldsIsntShown/local_circular_include_err.golden
=> Deal with the nondeterministic results from circular import detection

docs/reference-config-guide-v1.md, pkg/compare/compare.go, pkg/compare/compare_test.go, pkg/compare/correlator.go, pkg/compare/referenceV2.go, pkg/compare/testdata/ReferenceV2InlineCapturegroups/localWithDiffBetweenCapturegroupsout.golden, pkg/compare/testdata/ReferenceV2InlineCapturegroups/localWithDiffInFirstLineout.golden, pkg/compare/testdata/ReferenceV2InlineCapturegroups/localWithMismatchedCapturegroupsout.golden, pkg/compare/testdata/ReferenceV2InlineCapturegroups/localinvalidCapturegroupsLateDetectionerr.golden, pkg/compare/testdata/ReferenceV2InlineCapturegroups/localinvalidCapturegroupsLateDetectionout.golden, pkg/compare/testdata/ReferenceV2InlineCapturegroups/localout.golden, pkg/compare/testdata/ReferenceV2InlineCapturegroups/localwithDiffout.golden, pkg/compare/testdata/ReferenceV2InlineCapturegroups/reference/cm-invalid-capturegroups-late-detection.yaml, pkg/compare/testdata/ReferenceV2InlineCapturegroups/reference/cm-invalid-capturegroups.yaml, pkg/compare/testdata/ReferenceV2InlineCapturegroups/reference/cm-with-diff-between-capturegroups.yaml, pkg/compare/testdata/ReferenceV2InlineCapturegroups/reference/cm-with-diff-in-first-line.yaml, pkg/compare/testdata/ReferenceV2InlineCapturegroups/reference/cm-with-diff.yaml, pkg/compare/testdata/ReferenceV2InlineCapturegroups/reference/cm-with-mismatched-capturegroups.yaml, pkg/compare/testdata/ReferenceV2InlineCapturegroups/reference/cm.yaml, pkg/compare/testdata/ReferenceV2InlineCapturegroups/reference/metadata-invalid-capturegroups-late-detection.yaml, pkg/compare/testdata/ReferenceV2InlineCapturegroups/reference/metadata-invalid-capturegroups.yaml, pkg/compare/testdata/ReferenceV2InlineCapturegroups/reference/metadata-with-diff-between-capture-groups.yaml, pkg/compare/testdata/ReferenceV2InlineCapturegroups/reference/metadata-with-diff-in-first-line.yaml, pkg/compare/testdata/ReferenceV2InlineCapturegroups/reference/metadata-with-diff.yaml, pkg/compare/testdata/ReferenceV2InlineCapturegroups/reference/metadata.yaml, pkg/compare/testdata/ReferenceV2PerFieldMatcherValidation/localpathNotItTemplateerr.golden, pkg/compare/unstructured.go, pkg/compare/unstructured_test.go
- **Add stacktrace to test panic output**
- **Replace unstructured.NestedString with a copy that allows list traversal**
- **Perform field validation just-in-time for diff**
- **Excercise list traversal pathToKey for capturegroups testing**
=> unstructured nested list traversal

README.md
- **Consistent naming**
- **Add sytem-test build badge**
- **Update install instructions**
=> main readme update

Makefile, addon-tools/helm-convert/helm-convert.go, addon-tools/report-creator/report-creator.go, cmd/kubectl-cluster_compare.go, pkg/compare/compare.go, pkg/compare/testdata/NoInput/localerr.golden, pkg/compare/testdata/UserOverride/localfailOutputerr.golden, pkg/compare/testdata/UserOverride/localnoReasonGenerateerr.golden
=> CNF-16050: Add --version flag to cluster-compare and helpers

Makefile, addon-tools/helm-convert/helm-convert.go, addon-tools/report-creator/report-creator.go, cmd/kubectl-cluster_compare.go, pkg/compare/compare.go, pkg/compare/testdata/NoInput/localerr.golden, pkg/compare/testdata/UserOverride/localfailOutputerr.golden, pkg/compare/testdata/UserOverride/localnoReasonGenerateerr.golden
=> CNF-16338: [4.18 backport] Add --version flag to cluster-compare and helpers

OWNERS
=> Add Adhita Logan (adhil0) as reviewer and approver

hack/krew-bump.sh
=> Repair krew-bump script to auto-file the PR instead of opening a web browser

pkg/compare/compare.go
=> Fixup golangci-lint fixes for v1.63.4

go.mod
=> Advance to golang-1.23

docs/example/ClusterOperator.yaml, docs/example/ClusterVersion.yaml, docs/example/MachineConfigPool.yaml, docs/example/README.md, docs/example/metadata.yaml
Opening a PR to see if a minimal reference is possible to help users try out the cluster-compare plugin quickly on any cluster.
=> Minimal example reference for users 
